//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ActViewer.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ActViewer.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 1 - BILL OF RIGHTS, CONSTITUTION AND JUSTICE ACT
        ///
        ///PREFACE
        ///
        ///1.   This act was cited as the Bill of Rights, Constitution and Justice Act, MMXVII.
        ///2.   The short title for this act is Constitution Act, 2017.
        ///
        ///CONSTITUTION ACT
        ///
        ///1.   The divisions of the 3rd Kingdom of Baustralia—provinces—are made up of Holderton County, Mild Pond, Forest Creek, Norfolk, Flavora, Wooler, and Landspotter and the personal possessions of His Majesty (inc. HM’s District).
        ///2.   Any land except that under personal p [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1john1_1_original {
            get {
                return ResourceManager.GetString("1john1-1-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 2 - NATIONAL SYMBOLS ACT
        ///
        ///PREFACE
        ///
        ///1.   This act was cited as the National Symbols Act, MMXVII.
        ///2.   The short title for this act is National Symbols Act, 2017.
        ///
        ///NAMING CONVENTIONS
        ///
        ///1.   When writing the names of the nation, one must follow these guidelines:
        /// a)   In English:
        ///  i.   3ʳᵈ Kingdom of Baustralia
        ///  ii.  3rd Kingdom of Baustralia
        ///  iii. Baustralia
        ///  iv.  Third Kingdom of Baustralia
        ///  v.   THIRD KINGDOM OF BAVSTRALIA
        ///  vi.  BAVSTRALIA
        ///  vii. 3ᴿᴰ KINGDOM OF BAVSTRALIA
        ///  vi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1john1_2_original {
            get {
                return ResourceManager.GetString("1john1-2-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 3 - THE ACT TO ALLOW HIS MOST GRACIOUS MAJESTY TO AMEND THE SUCCESSION LAW TO BAR SIBLINGS AND ANCESTORS
        ///
        ///1.   This act was cited as the Modification Act to the Succession Law of Baustralia, HM-PPU-001.
        ///2.   The short title for this act is Modification Act to the Succession Law of Baustralia, 2017.
        ///3.   The Parliament resolves that due to crimes laid on the Princess of Wabasso, she will not ascend to the throne if it should fall upon her.
        ///4.   The Parliament resolves that due to a lack of belie [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _1john1_3_original {
            get {
                return ResourceManager.GetString("1john1-3-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 1 - AN ACT TO REPEAL ALL BILLS
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty wishes to restructure all laws, with this act, all previous bills shall all be repealed.
        ///This Act shall be known as Repeal Act, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and Successors of His Majesty, Kings and Queens of the Kingdom of Baustralia.
        ///
        ///TERMS
        ///
        ///These acts shall be repealed and shall have no affect over the people of Baustralia.
        ///.
        /// </summary>
        internal static string _2john1_1_original {
            get {
                return ResourceManager.GetString("2john1-1-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 10 - AN ACT TO MAKE PROVISION FOR AND IN CONNECTION WITH THE ENDING OF BAUSTRALIAN SOVEREIGNTY AND JURISDICTION OVER THE FOX ISLANDS
        ///
        ///TERMS
        ///
        ///1.   Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Lords Spiritual and Temporal, and Commons, in this present Parliament assembled, and by the authority of the same, as follows:—
        ///
        ///ENDING OF SOVEREIGNITY
        ///
        ///2.   As from 1 May 2019, His Majesty shall no longer have sovereignty or jurisdiction over any part of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_10_original {
            get {
                return ResourceManager.GetString("2john1-10-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 11 - AN ACT TO REPEAL THE MODIFICATIONS TO THE SUCCESSION LAW OF BAUSTRALIA AND REPLACE IT WITH A LESS RESTRICTIVE METHOD
        ///
        ///PREFACE
        ///
        ///1.   Whereas in the past, His Most Excellent and Gracious Majesty had put forth a bill barring Their Royal Highnesses from succession, he feels that it may be beneficial to revert to a standard law.
        ///2.   This Act shall be known as the Succession Law (Modifications, No. 2) Act, 2019
        ///
        ///TERMS
        ///
        ///3.   Their Royal Highnesses may reign as King or Queen of the Baustralia [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_11_amend1 {
            get {
                return ResourceManager.GetString("2john1-11-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 11 - AN ACT TO REPEAL THE MODIFICATIONS TO THE SUCCESSION LAW OF BAUSTRALIA AND REPLACE IT WITH A LESS RESTRICTIVE METHOD
        ///
        ///PREFACE
        ///
        ///1.   Whereas in the past, His Most Excellent and Gracious Majesty had put forth a bill barring Their Royal Highnesses from succession, he feels that it may be beneficial to revert to a standard law.
        ///2.   This Act shall be known as the Modification Act to the Succession Law of Baustralia, 2019
        ///
        ///TERMS
        ///
        ///3.   Their Royal Highnesses may reign as King or Queen of t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_11_original {
            get {
                return ResourceManager.GetString("2john1-11-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 12  - AN ACT REGARDING CITIZENSHIP IN BAUSTRALIA AND THE RIGHTS REVOKED BY CONVICTS OF LAW
        ///
        ///TERMS
        ///
        ///1.   Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Lords Spiritual and Temporal, and Commons, in this present Parliament assembled, and by the authority of the same, as follows:—
        ///
        ///DEFINITION
        ///
        ///2.   Citizens are those legally bound to Baustralia and its laws, and must submit to the rule of His Majesty, his heirs and successors, as well as the minist [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_12_original {
            get {
                return ResourceManager.GetString("2john1-12-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 13 - AN ACT TO MAKE PROVISION FOR AND IN CONNECTION WITH THE ENDING OF BAUSTRALIAN SOVEREIGNTY AND JURISDICTION OVER KAPREBURG
        ///
        ///TERMS
        ///
        ///1.   Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Lords Spiritual and Temporal, and Commons, in this present Parliament assembled, and by the authority of the same, as follows:—
        ///
        ///ENDING OF SOVEREIGNITY
        ///
        ///2.   As from 24 April 2019, His Majesty shall no longer have sovereignty or jurisdiction over any part of Kap [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_13_original {
            get {
                return ResourceManager.GetString("2john1-13-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 14 - AN ACT TO FORMALLY RECOGNIZE THE INDEPENDENCE OF RMHOANIA
        ///
        ///PREFACE
        ///
        ///Be it known that His Most Excellent and Gracious Majesty has, with the advice of His ministers, accepted the independence of London and sovereignty of Rmhoania.
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Rmhoania Act 2019.
        ///2.   The province of London shall be independent.
        ///3.   The sovereignty of Rmhoania shall not be affected by this Bill.
        ///4.   Citizens of Rmhoania may also serve as Regular and Reserve members of Hi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_14_original {
            get {
                return ResourceManager.GetString("2john1-14-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 15 - AN ACT TO REVERT THE CHANGES TO THE AIR FORCE BY THE SIXTH CHAPTER OF THE STATUTE OF THE PARLIAMENTARY SESSION THAT SAT IN THE 2ND YEAR OF THE REIGN OF KING JOHN I
        ///
        ///PREFACE
        ///
        ///As the strength of non-commissioned members in the Air Command has matched that of the remaining NCMs of the Baustralian Army, the Act cited 2 John 1 c. 6 is no longer required.
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Air Force Act 2019.
        ///2.   The Air Command shall become a service branch of the Baustralian Arme [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_15_original {
            get {
                return ResourceManager.GetString("2john1-15-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 16 - AN ACT TO ALLOW THE MONARCH TO PRACTICE WHATEVER RELIGION HE MAY WISH
        ///
        ///PREFACE
        ///
        ///Be it known that His Most Gracious and Excellent Majesty has set out in an Order-in-Council that all heirs and successors must be in communion with the Christian God.
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Religion (Throne) Act, 2019.
        ///2.   The succession law shall remain the same.
        ///3.   Heirs may become monarch regardless of what religion he may practice.
        ///4.   Heirs may also become monarch if they are [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_16_amend1 {
            get {
                return ResourceManager.GetString("2john1-16-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 16 - AN ACT TO ALLOW THE MONARCH TO PRACTICE WHATEVER RELIGION HE MAY WISH
        ///
        ///PREFACE
        ///
        ///Be it known that His Most Gracious and Excellent Majesty has set out in an Order-in-Council that all heirs and successors must be in communion with the Christian God.
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Religion Act 2019.
        ///2.   The succession law shall remain the same.
        ///3.   Heirs may become monarch regardless of what religion he may practice.
        ///4.   Heirs may also become monarch if they are atheist.        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_16_original {
            get {
                return ResourceManager.GetString("2john1-16-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 17 - AN ACT REGARDING THE SEPERATION OF PROVINCES OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///While reading, regard the Rmhoanian referendum and the first Chapter of the Statue of the Parliamentary Session that sat in the 1st year of the Reign of King John I.
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Separation Act 2019
        ///2.   A province, to be independent, must hold a referendum, and be approved by the Crown.
        ///3.   A full report must be sent to the Crown for the referendum to be regarded. 
        ///4.   The referendu [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_17_original {
            get {
                return ResourceManager.GetString("2john1-17-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 18 - AN ACT TO APPLY THE ABDICATION OF HER MAJESTY THE QUEEN OF EDSTMAE TO THE BAUSTRALIAN THRONE
        ///
        ///PREFACE
        ///
        ///Whereas Her Majesty by royal message declared she will irrevocably renounce the Throne of Edstmae for herself and her descendants as set out in the schedule of this Act. As she will inherit the throne of Baustralia and henceforth the throne of Edstmae,
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Abdication Act, 2019.
        ///2.   Immediately upon Royal Assent of this Act, Her Royal Highness t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_18_original {
            get {
                return ResourceManager.GetString("2john1-18-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 19 - AN ACT TO DEFINE THE NATIONAL CURRENCY OF BAUSTRALIA AND ITS VALUE IN RELATION TO PURE SILVER
        ///
        ///PREFACE
        ///
        ///1.   Whereas His Majesty has already set a standard for currency in Baustralia, it shall be defined in this Act.
        ///2.   This Act may be cited as the Boerc Act, 2019.
        ///
        ///BOERC
        ///
        ///3.   The currency of Baustralia is the Baustralian Boerc.
        /// a)   It is defined by the RIS as Boerc (Baustralian), BUB, 001.
        ///4.   The symbol for the Boerc is ᛒ and is described as the Old English rune meaning birch [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_19_original {
            get {
                return ResourceManager.GetString("2john1-19-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 2 - AN ACT TO REPLACE THE CONSTITUTION OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty does not like the current constitution, we, the parliament shall please him by, with the aid of a previous act, repeal the previous constitution and update it with this act.
        ///After the previous act came into effect, it invalidated the previous constitution and this one shall replace it.
        ///This Act shall be known as Constitution Act, 2018.
        ///Provisions of this Act referring to His Majesty the King exte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_2_amend1 {
            get {
                return ResourceManager.GetString("2john1-2-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 2 - AN ACT TO REPLACE THE CONSTITUTION OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty does not like the current constitution, we, the parliament shall please him by, with the aid of a previous act, repeal the previous constitution and update it with this act.
        ///After the previous act came into effect, it invalidated the previous constitution and this one shall replace it.
        ///This Act shall be known as Constitution Act, 2018.
        ///Provisions of this Act referring to His Majesty the King exte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_2_amend2 {
            get {
                return ResourceManager.GetString("2john1-2-amend2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 2 - AN ACT TO REPLACE THE CONSTITUTION OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty does not like the current constitution, we, the parliament shall please him by, with the aid of a previous act, repeal the previous constitution and update it with this act.
        ///After the previous act came into effect, it invalidated the previous constitution and this one shall replace it.
        ///This Act shall be known as Constitution Act, 2018.
        ///Provisions of this Act referring to His Majesty the King exte [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_2_original {
            get {
                return ResourceManager.GetString("2john1-2-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 20 - AN ACT REGARDING THE COUNTERFEITING OF THE BOERC, CEN, AND DÆG
        ///
        ///PREFACE
        ///
        ///1.   This act shall be added to the Baustralian Criminal Code.
        ///2.   This Act may be cited as the Counterfeit Act, 2019.
        ///
        ///TERMS
        ///
        ///3.   Counterfeit currency is illegal in Baustralia and is punishable by fine up to 200% of the value of currency made.
        ///4.   One found guilty of counterfeiting currency must personally pay the crown one Boerc..
        /// </summary>
        internal static string _2john1_20_original {
            get {
                return ResourceManager.GetString("2john1-20-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 21 - AN ACT REGARDING THE BOERC AND THE MEASURES TO BE CHANGE THE VALUE BASED ON GOLD IF THE SPOT PRICE OF SILVER FAILS
        ///
        ///PREFACE
        ///
        ///1.   Whereas His Majesty wishes not for the failure of the Boerc to affect the economy a great deal, this Act will lay out the measures to take.
        ///2.   This Act shall be cited as the Boerc Measures Act, 2019.
        ///3.   In the United Kingdom, the pound sterling reduced in price when gold was taking the place of silver. This made the silver coins token coins, and as such, th [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_21_original {
            get {
                return ResourceManager.GetString("2john1-21-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 22 - AN ACT REGARDING HIS MAJESTY’S ABILITY TO DECLARE WAR ON STATES AS HE SO WISHES; REGARDING THE RECIPROCATION OF DECLARATIONS OF WAR; REGARDING THE CONDUCT OF WAR
        ///
        ///PREFACE
        ///
        ///1.   Whereas His Majesty can declare war on states as he wishes, he does not need to receive permission from Parliament.
        ///2.   It shall be noted that His Most Excellent Majesty does request permission as of now.
        ///3.   This Act shall be cited as the War Powers Act, 2019.
        ///
        ///HIS MAJESTY’S ABILITY
        ///
        ///4.   His Majesty must re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_22_original {
            get {
                return ResourceManager.GetString("2john1-22-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 23 - AN ACT REGARDING TREASON AND THE RIGHTS GIVEN TO THOSE TRIED FOR HIGH TREASON
        ///
        ///PREFACE
        ///
        ///1.   This Act shall abolish the common law practice of trying persons for treason or high treason.
        ///2.   This Act shall be known as the Treason Act, 2019.
        ///3.   This shall be compiled into the Criminal Code.
        ///
        ///TERMS
        ///
        ///4.   Petty treason shall be defined as the attempt to kill or cause bodily harm to one’s superiors
        ///5.   Treason shall be defined as the attempt to kill or cause bodily harm to any govern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_23_original {
            get {
                return ResourceManager.GetString("2john1-23-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 24 - AN ACT REGARDING THE PRACTICE OF RELIGION AND THE RIGHTS GIVEN TO NEW RELIGIOUS MOVEMENTS
        ///
        ///PREFACE
        ///
        ///1.   Be it known that, after the independence of Romonia, the Church of DeBruinism was founded.
        ///2.   Whereas His Majesty wishes to draw the line between what counts as religions, this Act shall be written.
        ///3.   This Act shall be known as the Religion (Practice) Act, 2019.
        ///4.   Religions not listed below may still be religions according to the Crown and government, however are not distingui [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_24_original {
            get {
                return ResourceManager.GetString("2john1-24-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 25 - AN ACT TO DISSOLVE HIS ROYAL MARINES AND REPLACE IT WITH THE NAVAL AMPHIBIOUS ARM SIMILAR IN STRUCTURE TO THE NAVAL AIR ARM
        ///
        ///PREFACE
        ///
        ///1.	 Whereas the Marines have dropped in NCO strength to seven (7), His Majesty wishes for the Marines to muster in the ranks with the navy just as marine officers muster with naval officers.
        ///2.	 This Act shall be known as the Marines Act, 2019.
        ///
        ///TERMS
        ///
        ///3.	 His Royal Marines shall be dissolved, and their strength muster with the navy.
        ///4.	 They will all b [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_25_original {
            get {
                return ResourceManager.GetString("2john1-25-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 26 - AN ACT TO DISSOLVE HIS ROYAL AIR FORCE AND REPLACE IT WITH HIS ROYAL FLYING CORPS AND THE NAVAL AIR ARM 
        ///
        ///PREFACE
        ///
        ///1.	 Whereas the Air Force have dropped in NCO strength to four (4), His Majesty’s House of Lords Temporal and Spiritual wishes for the air force to muster in the ranks with the navy.
        ///2.   This Act shall be known as the Air Force Dissolution Act, 2019.
        ///
        ///TERMS
        ///
        ///3.	 His Royal Flying Corps (HRFC) shall be formed under command of the Army
        ///4.	 His Royal Air Force shall be disso [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_26_original {
            get {
                return ResourceManager.GetString("2john1-26-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 27 - AN ACT REGARDING TERMS OF ELECTION
        ///
        ///PREFACE
        ///
        ///1.	 Whereas by the Constitution, His Majesty will appoint a Prime Minister and his Cabinet through a quadrennial election, with this Act shall be changed to an annual election.
        ///2.   This Act shall be known as the Fixed Terms Election Act.
        ///
        ///TERMS
        ///
        ///3.	 Elections shall take place every year on the same date as before, 20 June..
        /// </summary>
        internal static string _2john1_27_original {
            get {
                return ResourceManager.GetString("2john1-27-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 28 - AN ACT RESPECTING THE BAUSTRALIAN DOMINIONS AND ACTS OF PARLIAMENT OF BAUSTRALIA RELATING TO THE DOMINIONS
        ///
        ///PREFACE
        ///
        ///1.	 Be it enacted by His Most Gracious and Excellent Majesty and by the consent of the House of Commons as follows
        ///
        ///TERMS
        ///
        ///2.	 All Acts passed by the Parliament of Baustralia shall affect the dominions.
        ///3.	 Acts affecting the whole of the Baustralian Empire shall be known as Primary Legislation
        ///4.	 Acts affecting Baustralia or one of the dominions, or affecting the Empi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_28_original {
            get {
                return ResourceManager.GetString("2john1-28-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 29 - AN ACT TO GIVE EFFECT TO HER MAJESTY&apos;S DECLARATION OF ABDICATION; AND FOR PURPOSES CONNECTED THEREWITH
        ///
        ///PREFACE
        ///
        ///1.	 In accordance with the Dominion (Legislation) Act, 2 John 1 c. 27 the Edstmanian Act 1 Kat. 1 &amp; 1 John 1 c. 1 shall be repealed, but have no effect on the throne.
        ///2.	 This Act shall be known as Her Majesty’s Declaration of Abdication Act (Edstmae) 2019.
        ///3.	 This Act will supplement the Abdication Act, 2 John 1 c. 18.
        ///4.	 This Act shall extend to Edstmae only.
        ///
        ///SCHEDULE
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_29_original {
            get {
                return ResourceManager.GetString("2john1-29-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 3 - AN ACT TO DEFINE THE NATIONAL SYMBOLS OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas the Parliament of Baustralia has repealed all the acts of Parliament for restructuring, we, the Parliament are issuing this act, to declare all national symbols.
        ///This Act shall be known as National Symbols Act, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and Successors of His Majesty, Kings and Queens of the Kingdom of Baustralia.
        ///
        ///FLAG
        ///
        ///-HORIZONTAL HOISTING
        ///
        ///The flag of  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_3_original {
            get {
                return ResourceManager.GetString("2john1-3-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 30 - AN ACT REGARDING MARTIAL LAW AND THE PUNISHMENTS ASSOCIATED THEREWITH
        ///
        ///PREFACE
        ///
        ///1.   Whereas the Baustralian Armed Forces must have punishments for those committing crimes in military eyes, this Act shall serve this.
        ///2.   This Act shall be cited as the Military Law Act, 2019
        ///
        ///CRIMES
        ///
        ///2.   Abandonment
        /// a)   The act of being absent, away without leave (AWOL), or adrift, or departing from his post.
        /// b)   The punishment, proven guilty by courts-martial, shall be demotion in rank, or deco [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_30_original {
            get {
                return ResourceManager.GetString("2john1-30-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 4 - AN ACT TO MODIFY THE SUCCESSION LAW OF BAUSTRALIA TO DISALLOW ANY KIN, LESS DESCENDANTS OF JOHN I, FROM REIGNING OVER BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty wishes to keep the throne of Baustralia alive, His Most Gracious Majesty wishes to bar anyone who is not a descendant of His Majesty from reigning.
        ///This Act shall be known as the Succession Law (Modifications) Act, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and Successors of [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_4_amend1 {
            get {
                return ResourceManager.GetString("2john1-4-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 4 - AN ACT TO MODIFY THE SUCCESSION LAW OF BAUSTRALIA TO DISALLOW ANY KIN, LESS DESCENDANTS OF JOHN I, FROM REIGNING OVER BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///Whereas His Most Excellent Majesty wishes to keep the throne of Baustralia alive, His Most Gracious Majesty wishes to bar anyone who is not a descendant of His Majesty from reigning.
        ///This Act shall be known as Modification Act to the Succession Law of Baustralia, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_4_original {
            get {
                return ResourceManager.GetString("2john1-4-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 5 - AN ACT TO RENAME HIS ROYAL ARMY TO BAUSTRALIAN ARMY
        ///
        ///TERMS
        ///
        ///Whereas His Majesty wishes for the Armed Forces to be more universal, the Army shall be renamed Baustralian Army.
        ///This Act shall be known as Army Act, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and Successors of His Majesty, Kings and Queens of the Kingdom of Baustralia..
        /// </summary>
        internal static string _2john1_5_original {
            get {
                return ResourceManager.GetString("2john1-5-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 6 - AN ACT TO MAKE HIS ROYAL AIR FORCE SUBORDINATE TO THE BAUSTRALIAN ARMY
        ///
        ///TERMS
        ///
        ///Whereas His Majesty wishes for the Baustralian Army to be higher in strength, His Royal Air Force shall become a command of the Baustralian Army, known as the Air Command.
        ///This Act shall be known as Air Force Act, 2018.
        ///Provisions of this Act referring to His Majesty the King extend also to the Heirs and Successors of His Majesty, Kings and Queens of the Kingdom of Baustralia..
        /// </summary>
        internal static string _2john1_6_original {
            get {
                return ResourceManager.GetString("2john1-6-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAOTER 7 - AN ACT REGARDING NATIONAL HONOURS, AWARDS, DECORATIONS, AND PEERAGES OF BAUSTRALIA
        ///
        ///PREFACE
        ///
        ///This Act shall be known as Orders, medals, and decorations of Baustralia Act, 2019.
        ///
        ///DEFINITIONS
        ///
        ///Class 1 awards shall encompass orders of Baustralia.
        ///Class 2 awards shall encompass high honours of Baustralia.
        ///Class 3 awards shall encompass medals of Baustralia.
        ///Class 4 awards shall encompass military decorations of Baustralia.
        ///Class 4A awards shall be high military decorations, while class 4 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_7_original {
            get {
                return ResourceManager.GetString("2john1-7-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 8 - AN ACT REGARDING THE USE OF ALL STRAINS OF CANNABIS
        ///
        ///PREFACE
        ///
        ///1.   This act shall be added into a compilation known as the Baustralian Criminal Code.
        ///2.   This act shall be known as the Cannabis Act, 2019
        ///
        ///TERMS
        ///
        ///3.   Cannabis shall refer to all strains, i.e.
        /// a)   Cannabis sativa
        /// b)   Cannabis indica
        /// c)   Cannabis ruderalis
        /// d)   All cross-bred strains
        ///4.   All cannabis products are considered Class I narcotics, and shall be considered illegal, and are not to be used by the publ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_8_original {
            get {
                return ResourceManager.GetString("2john1-8-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 9 - AN ACT TO REVOKE THE DUKEDOM OF NORTHUMBRIA FROM THE DUKE
        ///
        ///1.   The title, honours, and salary associated with the dukedom shall be revoked.
        ///2.   This Act shall be known as “Dukedom of Northumbria Act”.
        ///3.   The title for the Duke shall be revoked because of withdrawal about the revocation procedure. Id est the Duke was not told that the title could not be revoked on request.
        ///4.   In addition, the Government of Ikonia ruled that all connections between Ikonia and Baustralia are ceased, incl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _2john1_9_original {
            get {
                return ResourceManager.GetString("2john1-9-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 1 - AN ACT REGARDING THE USE OF ALL STRAINS OF CANNABIS; TO REPEAL THE ACT IN THE STATUE OF PARLIAMENT THAT SAT IN THE 2ND YEAR OF THE REIGN OF JOHN I, CHAPTER 8
        ///
        ///PREFACE
        ///
        ///1.   This act shall repeal the Cannabis Act, 2019, 2 John 1 c. 8
        ///2.   This act shall be known as the Cannabis Act (Legalization), 2019
        ///3.   The provisions for cannabis in the Criminal Code shall be struck off.
        ///
        ///
        ///TERMS
        ///
        ///4.   Cannabis shall refer to all strains, i.e. 2 John 1 c. 8
        /// a)   Cannabis sativa
        /// b)   Cannabis in [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_1_original {
            get {
                return ResourceManager.GetString("3john1-1-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 10 - AN ACT RESPECTING ALL FIREARMS CONCEALED ON THE PERSON, ON AN ANIMAL, WITHIN A BAG, OR ELSEWHERE; REGARDING THE PUNISHMENT FOR THE CONVICTED; REGARDING THE TERMS FOR PROHIBITION
        ///
        ///Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Commons, in this present Parliament assembled, and by the authority of the same, as follows:— 
        ///
        ///1.   This Act may be cited as the Concealed Firearms Act, 2019.
        ///
        ///DEFINITIONS
        ///
        ///2.   ‘Concealed’ shall refer to any firearm  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_10_original {
            get {
                return ResourceManager.GetString("3john1-10-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 11 - AN ACT RESPECTING THE “WRYTHE CONVENTION ON THE PREVENTION AND DENOUNCING OF FALSEHOODS WITHIN THE COMMUNITY OF SMALL STATES AND NATIONS” AND TO SIGN AS A KINGDOM THE DOCUMENT FORESTATED
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty and by the consent of the Commons as follows:-
        ///1.   This Act shall come into force immediately.
        ///2.   This Act does not sign or force His Most Gracious and Excellent Majesty to sign the document, but to serve as a formal recognition of the document it [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_11_original {
            get {
                return ResourceManager.GetString("3john1-11-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 12 - AN ACT TO PREVENT ACTS OF PARLIAMENT FROM TAKING EFFECT FROM A TIME PRIOR TO THE PASSING THEREOF
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty and by the consent of the Commons as follows:-
        ///1.   As it is legal fiction that a session of Parliament lasts one day, Acts without a set date by containing the words &quot;This Act shall come into effect immediately, that is, upon Royal Assent&quot;, &quot;This Act shall come into effect on [x date]&quot; or &quot;This Act shall come into effect on [y event]&quot;, Ac [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_12_original {
            get {
                return ResourceManager.GetString("3john1-12-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 13 - AN ACT TO AMEND THE ACT OF PARLIAMENT REGARDING THE UNION WITH QUEBEC DUE TO A CHANGE IN NAME AND GOVERNMENT
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty and by the consent of the Commons as follows:-
        ///1.   Whereas the Second Kingdom of Quebec and Versaillies has changed their name to the United People&apos;s Federation of Quebec, the Union with Quebec Act, 3 John 1 c. 9 must be amended for the Act to work in the future.
        ///2.   This Act shall be known as the Union with Quebec (Modifica [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_13_original {
            get {
                return ResourceManager.GetString("3john1-13-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 14 - AN ACT TO ALLOW THE MONARCH TO PASS ANY ACT WITHOUT THE CONSENT OF THE COMMONS, LORDS TEMPORAL AND SPIRITUAL, OR ANY LEGISLATURE
        ///
        ///1.   Be it enacted by His Most Gracious Majesty and by the consent of the Commons as follows:
        ///2.   This Act shall be known as the Monarchy (Powers) Act, 2019.
        ///3.   His Majesty shall be able to create legislation, allocate a bill citation, and assent any legislation without any consent from the Commons, Lords Temporal and Spiritual, or other legislature.
        ///4.   His [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_14_original {
            get {
                return ResourceManager.GetString("3john1-14-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 15 - AN ACT TO CEDE THREE ACRES OF THE NINETEEN ACRES OF THE EMPIRE OF OSTREUM TO THE PEOPLE’S FEDERATION OF QUEBEC UNDER THE NAME OF LITIHANUA
        ///
        ///Be it enacted by His Most Gracious Majesty the following:
        ///1.   The People’s Federation of Quebec shall receive three acres of Ostreum centered on the widest point of Tentacion Creek that is a foot away from John Road. 
        ///2.   The south-by-south-south-eastern border shall be a tri-point border with Canada, Dominion of; Ostreum, Empire of; and Quebec, Peopl [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_15_original {
            get {
                return ResourceManager.GetString("3john1-15-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 16 - AN ACT REGARDING PROSTITUTION
        ///
        ///PREFACE
        ///
        ///1.   This Act shall be known as the Prostitution Act, 2019.
        ///
        ///TERMS
        ///
        ///2.   This Act shall extend to the whole Empire, less Ostreum.
        ///3.   Prostitution shall be defined as any sexual act performed for monetary gain.
        ///4.   Prostitution shall be considered illegal.
        ///5.   The fine shall be one million (1,000,000) boercs..
        /// </summary>
        internal static string _3john1_16_amend1 {
            get {
                return ResourceManager.GetString("3john1-16-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 16 - AN ACT REGARDING PROSTITUTION
        ///
        ///PREFACE
        ///
        ///1.   This Act shall be known as the Prostitution Act, 2019.
        ///
        ///TERMS
        ///
        ///2.   Prostitution shall be defined as any sexual act performed for monetary gain.
        ///3.   Prostitution shall be considered illegal.
        ///4.   The fine shall be one million (1,000,000) boercs..
        /// </summary>
        internal static string _3john1_16_original {
            get {
                return ResourceManager.GetString("3john1-16-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 17 - AN ACT TO DE-EXTEND THE PROSTITUTION ACT IN OSTREUM
        ///
        ///Be it enacted by His Most Gracious Majesty and by the consent of the Commons as follows:
        ///1.   This Act shall be known as the Prostitution (Legalization) Act (Ostreum), 2019.
        ///2.   In the Prostitution Act, after paragraph one, a paragraph shall be added stating:-
        /// 2.   This Act shall extend to the whole Empire, less Ostreum..
        /// </summary>
        internal static string _3john1_17_original {
            get {
                return ResourceManager.GetString("3john1-17-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 18 - AN ACT REPEALING THE UNION WITH QUEBEC ACT (BAUSTRALIA)
        ///
        ///Be it enacted by His Most Gracious Majesty and by the consent of the Commons as follows:
        ///1.   The Union with Quebec Act (Baustralia) shall be repealed in full.
        ///2.   The Union with Quebec (Modifications) Act (Baustralia) shall be repealed in full.
        ///3.   This Act shall be known as the Union with Quebec (Repeal) Act (Baustralia), 2019
        ///4.   This Act shall extend to Baustralia only..
        /// </summary>
        internal static string _3john1_18_original {
            get {
                return ResourceManager.GetString("3john1-18-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 19 - AN ACT RETURNING THE PROVINCE OF TAYLOR TO THE PEOPLE’S FEDERATION OF QUEBEC; REGARDING THE STATUS OF THE CITIZENS RESIDING THEREIN; REGARDING THE MEMBER OF PARLIAMENT THEREOF
        ///
        ///Be it enacted by His Most Gracious Majesty and by the consent of the Commons as follows:
        ///1.   This Act shall be known as the Taylor Act, 2019.
        ///2.   This Act shall come into effect as dictated in the Schedule of this Act.
        ///
        ///RETURN OF TAYLOR
        ///
        ///3.   The Province of Taylor shall become sovereign and be amalgamated into [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_19_original {
            get {
                return ResourceManager.GetString("3john1-19-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 2 - AN ACT REGARDING THE USE OF NARCOTICS; TO DEFINE THE NARCOTICS THAT ARE LEGAL; TO DEFINE THE NARCOTICS THAT ARE ILLEGAL; TO DEFINE THE AGE LIMITS FOR ALCOHOL        ///        ///PREFACE        ///        ///1.   Alcohol, as defined in this scope, is any beverage containing more than 0.5%/vol, id est more than half a percent by volume of ethanol.        ///2.   Tobacco refers to all products with the tobacco leaf and its extracts, or chemically produced nicotine, id est nicotine salt or free base nicotine.        ///3.   LSD is defined as lysergic acid d [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_2_original {
            get {
                return ResourceManager.GetString("3john1-2-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 20 - AN ACT REGARDING THE RESIGNATION OF MINISTERS OF THE CROWN, MEMBERS OF PARLIAMENT, AND OTHER OFFICERS OF THE CROWN
        ///
        ///Be it enacted by His Most Gracious Majesty and by the consent of the Commons as follows:
        ///1.   This Act shall be known as the Resignation Act, 2019.
        ///2.   “Persons concerned” shall refer to Ministers of the Crown, Members of Parliament, and other officers of the crown (including Members of His Most Gracious and Excellent Majesty’s Baustralian Armed Forces).
        ///3.   Persons concern [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_20_original {
            get {
                return ResourceManager.GetString("3john1-20-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 21 - AN ACT RATIFYING THE CHARTER OF THE GRAND UNIFIED MICRONATIONAL AND PURPOSES CONNECTED THEREOF
        ///
        ///Be it enacted by His Most Gracious Majesty and with the Consent of the Commons as follows:-
        ///1.   This Act shall be known as the Grand Unified Micronational (Ratification) Act, 2019.
        ///2.   This Act shall ratify the Charter of the Grand Unified Micronational.
        ///3.   This Act shall not replace His Majesty’s signature but rather recognize it for the Empire..
        /// </summary>
        internal static string _3john1_21_original {
            get {
                return ResourceManager.GetString("3john1-21-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 22 - AN ACT REGARDING THE DETERMINATION OF HIS MAJESTY’S MOST LOYAL OPPOSITION WITHIN THE PARLIAMENT OF BAUSTRALIA
        ///
        ///Be it enacted by His Most Gracious Majesty and with the Consent of the Commons as follows:-
        ///1.   Should the case arise that two or more parties shall tie for the position of His Majesty’s Loyal Opposition, the following may be taken into account.
        /// a)   Combined salaries of the Members including salaries from the military.
        /// b)   Members at the start of session.
        ///2.   Should the cas [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_22_original {
            get {
                return ResourceManager.GetString("3john1-22-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 23 - AN ACT REGARDING THE ROLE OF HIS MAJESTY’S MOST LOYAL OPPOSITION WITHIN THE PARLIAMENT OF BAUSTRALIA
        ///
        ///Be it enacted by His Most Gracious Majesty and with the Consent of the Commons as follows:-
        ///1.   His Majesty’s Most Loyal Opposition, hereafter referred to as the Opposition, is the party within Parliament who has the second-highest number of seats. In the case of a tie, the Act regarding the determination of His Majesty’s Most Loyal Opposition within the Parliament of Baustralia shall be ta [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_23_original {
            get {
                return ResourceManager.GetString("3john1-23-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 24 - AN ACT REGARDING AND ESTABLISHING THE DOMINION OF WHISKEY ISLANDS
        ///
        ///Be it enacted by His Most Gracious and Excellency the following:-
        ///1.   Established is the Dominion of Whiskey Islands.
        ///2.   The Whiskey Islands shall be represented in Parliament by the Minister for Foreign Affairs..
        /// </summary>
        internal static string _3john1_24_original {
            get {
                return ResourceManager.GetString("3john1-24-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 25 - AN ACT REGARDING THE NATIONAL SYMBOLS OF WHISKEY ISLANDS
        ///
        ///Be it enacted by His most Excellent Majesty and with the consent of the Commons as follows:-
        ///
        ///PREFACE
        ///
        ///1.   This Act, less section 5 shall extend to Whiskey Islands only.
        ///2.   Section 5 shall extend to the whole empire.
        ///3.   This Act shall be known as the National Symbols Act (Whiskey Islands), 2019.
        ///
        ///TERMS
        ///
        ///4.   The flag of Whiskey Islands shall be a Baustralian red ensign, that is a red flag with the Baustralian flag in the [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_25_original {
            get {
                return ResourceManager.GetString("3john1-25-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 26 - AN ACT REGARDING THE MINISTERS OF THE CROWN; REGARDING THE CHANGE OF MINISTRIES OVER TO OFFICES; REGARDING THE CHANGE OF TITLE OF “MINISTER FOR” TO “SECRETARY OF STATE”; REGARDING THE FOUNDING OF OFFICES FOR THE DOMINIONS; REGARDING THE DISSOLUTION OF THE IMPERIAL AFFAIRS OFFICE; AND PURPOSES CONNECTED THEREWITH
        ///
        ///Be it enacted by His most Excellent Majesty and with the consent of the Commons as follows:-
        ///
        ///PREFACE
        ///
        ///1.   This Act shall be known as the Secretary of State Act, 2019.
        ///2.   Thi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_26_original {
            get {
                return ResourceManager.GetString("3john1-26-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 27 - AN ACT TO RETRIEVE THE DISSOLVED FITHUANIA SOCIALIST REPUBLIC FROM THE REPUBLIC OF QUEBEC; MERGING IT WITH BAUSTRALIAN OSTREUM
        ///
        ///Be it enacted by His Most Excellent Majesty the following:-
        ///
        ///PREFACE
        ///
        ///1.   Fithuania, Socialist Republic of, was dissolved by the Republic of Quebec.
        ///2.   As a gift from Baustralia, it shall be taken back.
        ///3.   This Act shall be known as the Mayhew (Claim) Act, 2019.
        ///
        ///TERMS
        ///
        ///4.   The land shall merge with Baustralian Ostreum within the Empire of Ostreum.
        ///5 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_27_amend1 {
            get {
                return ResourceManager.GetString("3john1-27-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 27 - AN ACT TO RETRIEVE THE DISSOLVED FITHUANIA SOCIALIST REPUBLIC FROM THE REPUBLIC OF QUEBEC; MERGING IT WITH BAUSTRALIAN OSTREUM
        ///
        ///Be it enacted by His Most Excellent Majesty the following:-
        ///
        ///PREFACE
        ///
        ///1.   Fithuania, Socialist Republic of, was dissolved by the Republic of Quebec.
        ///2.   As a gift from Baustralia, it shall be taken back.
        ///3.   This Act shall be known as the Mayhew Act, 2019.
        ///
        ///TERMS
        ///
        ///4.   The land shall merge with Baustralian Ostreum within the Empire of Ostreum.
        ///5.   The  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_27_original {
            get {
                return ResourceManager.GetString("3john1-27-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 28 - AN ACT REGARDING THE DOMINIONS AND THEIR GOVERNMENT
        ///
        ///Be it enacted by His Most Excellent and Gracious Majesty as follows:-
        ///1.   The Governments of the Dominions shall be hereby dissolved.
        ///2.   Dominions shall be solely represented by a Lord Governor and a Secretary of State.
        ///3.   The Lord, or Peeress in the case of a female peer, Governor is a peer overseeing a Dominion and the representative in the House of Lords.
        /// a)   The Lord Governor in Ostreum shall be called Viceroy and Lord/Peeres [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_28_original {
            get {
                return ResourceManager.GetString("3john1-28-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 29 - AN ACT REGARDING THE COUNTY OF MAYHEW AND THE CLAIMS THEREON BY THE PEOPLE’S FEDERATION OF QUEBEC; TO AMEND THE MAYHEW ACT’S SHORT TITLE
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty as follows:-
        ///1.   This Act shall be known as the Mayhew (Annulment) Act, 2019.
        ///2.   The Mayhew Act, paragraph 3, shall read: “This Act shall be known as the Mayhew (Claim) Act, 2019.”
        ///3.   Whereas the government of Quebec has made an error in reporting the dissolution of all but Fithiuanian SR and  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_29_original {
            get {
                return ResourceManager.GetString("3john1-29-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 3 - AN ACT REGARDING THE PUNISHMENT OF INFORMANTS WITHIN WANGATANGIA
        ///
        ///PREFACE
        ///
        ///1.   This Act shall be known as the Informants Act (Wangatangia), 2019.
        ///2.   This Act shall extend only to Wangatangia.
        ///
        ///TERMS
        ///
        ///3.   An informant may also be known by the colloquial term “snitch.”
        ///4.   Informants in Wangatangia shall be punished by a 1,000 Wangatang Boerc fine.
        ///5.   This alludes to the motto “snitches are bitches.”.
        /// </summary>
        internal static string _3john1_3_original {
            get {
                return ResourceManager.GetString("3john1-3-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 30 - AN ACT DESCRIBING THE CALENDRIAL SYSTEM OF BAUSTRALIA; REGARDING THE REGNAL CALENDAR
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty as follows:-
        ///1.   This Act shall be known as the Calendar Act, 2019.
        ///
        ///GREGORIAN AND JULIAN CALENDAR SYSTEMS
        ///
        ///2.   The Parliament of Baustralia, and all governmental offices shall adopt and use the Gregorian calendar.
        ///3.   The Julian calendar must not be used for official or legal purposes.
        ///4.   The Julian calendar is not banned and can be used f [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_30_original {
            get {
                return ResourceManager.GetString("3john1-30-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 31 - AN ACT ESTABLISHING FORMALLY THE BAUSTRALIAN NEWS NETWORK
        ///
        ///BE IT ENACTED by His Most Gracious and Excellent Majesty the follows:
        ///1.   Created and chartered is the Baustralian News Network
        ///2.   Formed already, this Act serves to recognize it, and create it through legislature.
        ///3.   This Act shall be known as the Baustralian News Network Act, 2019..
        /// </summary>
        internal static string _3john1_31_original {
            get {
                return ResourceManager.GetString("3john1-31-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 32 - AN ACT TO DISSOLVE ALL ONE MAN PARTIES AND TO PREVENT THE CREATION OF THE AFOREMENTIONED PARTIES
        ///
        ///Be it enacted by His Most Gracious and Excellent Majesty and with the Consent of the Commons as follows:-
        ///1.   Men who create their own parties for the benefit of themselves is selfish.
        ///2.   A one-man party cannot function properly with only one member and it may be seen as a man voting for the benefit of himself, and not the people.
        ///3.   These parties cannot be registered with His Royal Gover [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_32_original {
            get {
                return ResourceManager.GetString("3john1-32-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to NOTE, SMALL CAPITALS ARE NOT DISPLAYED HERE (*)
        ///
        ///CHAPTER 33 - AN ACT REGARDING THE INTERPRETATION OF BILLS AND ACTS OF THE PARLIAMENT OF BAUSTRALIA AND PURPOSES CONNECTED THEREWITH
        ///
        ///PREFACE
        ///
        ///Be it enacted* by His Most Gracious and excellent Majesty and the Commons assembled, the follows:-
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Interpretation Act, 2019.
        ///2.   Interpretation of Bills and Acts are as follows:
        /// a)   Act* shall refer to an Act of the Parliament of Baustralia.
        /// b)   Act shall ref [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_33_original {
            get {
                return ResourceManager.GetString("3john1-33-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 34 - AN ACT RESTRUCTURING ALL DOMINIONS OF BAUSTRALIA INTO COLONIES AND PURPOSES CONNECTED THEREWITH
        ///
        ///PREFACE
        ///
        ///Be it enacted by His Most Gracious and excellent Majesty, the follows:-
        ///
        ///TERMS
        ///
        ///1.   This Act shall be known as the Colony Act, 2019.
        ///2.   Colonies shall be designated as territories unable to form a government due to population issues.
        ///3.   Dominions shall be self-governing, and do so independent of the Parliament of Baustralia.
        ///4.   As such, all dominions of Baustralia, includi [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_34_original {
            get {
                return ResourceManager.GetString("3john1-34-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 35 - AN ACT TO END THE OFFICIAL OWNERSHIP AND BAUSTRALIAN CONTROL OVER ORGANIZATION KNOWN AS THE LEAGUE OF NATIONS TO THE SOCIALIST STATE OF PALOMA
        ///
        ///Be it enacted by the King&apos;s most Excellent Majesty, by and with the advice and consent of the Commons, in this present Parliament assembled, and by the authority of the same, as follows :—
        ///1.   Baustralia will cease ownership of the League of Nations and its symbolics.
        ///2.   Baustralia will hand over the organization to the Socialist State of Paloma. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_35_original {
            get {
                return ResourceManager.GetString("3john1-35-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 4 - AN ACT REGARDING THE NATIONAL SYMBOLS OF THE BAUSTRALIAN ANTARCTIC TERRITORY
        ///
        ///PREFACE
        ///
        ///1.   This Act, less section 5 shall extend to the Baustralian Antarctic Territory only.
        ///2.   Section 5 shall extend to the whole empire.
        ///3.   This Act shall be known as the National Symbols Act (Baustralian Antarctic Territory), 2019.
        ///
        ///TERMS
        ///
        ///4.   The flag of the BAT shall be a Baustralian red ensign, that is a red flag with the Baustralian flag in the canton, with a flat rendering of Antarctica in t [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_4_original {
            get {
                return ResourceManager.GetString("3john1-4-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 5 - AN ACT REGARDING THE NATIONAL SYMBOLS OF EDSTMAE
        ///
        ///PREFACE
        ///
        ///1.   This Act, less section 5 shall extend to Edstmae only.
        ///2.   Section 5 shall extend to the whole empire.
        ///3.   This Act shall be known as the National Symbols Act (Edstmae), 2019.
        ///
        ///Terms
        ///
        ///4.   The flag of Edstmae shall be a Baustralian red ensign, that is a red flag with the Baustralian flag in the canton, with the York Rose in the fly.
        ///5.   The flag shall be treated with the same respect as the Baustralian flag.
        ///6.   The  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_5_original {
            get {
                return ResourceManager.GetString("3john1-5-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 6 - AN ACT REGARDING THE NATIONAL SYMBOLS OF OSTREUM
        ///
        ///PREFACE
        ///
        ///1.   This Act, less section 5 shall extend to Ostreum only.
        ///2.   Section 5 shall extend to the whole empire.
        ///3.   This Act shall be known as the National Symbols Act (Ostreum), 2019.
        ///
        ///TERMS
        ///
        ///4.   The flag of Ostreum shall be a Baustralian red ensign, that is a red flag with the Baustralian flag in the canton, with the escutcheon in the fly.
        ///5.   The flag shall be treated with the same respect as the Baustralian flag.
        ///6.   The [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_6_original {
            get {
                return ResourceManager.GetString("3john1-6-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 7 - AN ACT REGARDING THE NATIONAL SYMBOLS OF WANGATANGIA
        ///
        ///PREFACE
        ///
        ///1.   This Act, less section 5 shall extend to Wangatangia only.
        ///2.   Section 5 shall extend to the whole empire.
        ///3.   This Act shall be known as the National Symbols Act (Wangatangia), 2019.
        ///
        ///TERMS
        ///
        ///4.   The flag of Wangatangia shall be a Baustralian red ensign, that is a red flag with the Baustralian flag in the canton, with the escutcheon in the fly.
        ///5.   The flag shall be treated with the same respect as the Baustralian [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_7_original {
            get {
                return ResourceManager.GetString("3john1-7-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 8
        ///AN ACT RESPECTING SHORT TITLES OF TWO ACTS PASSED IN THE 2ND YEAR OF HIS MAJESTY’S REIGN RESPECTING MODIFICATIONS TO THE SUCCESSION LAW
        ///
        ///Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Commons, in this present Parliament assembled, and by the authority of the same, as follows:— 
        ///
        ///1.   This Act may be cited as the Short Titles Act, 2019.
        ///2.   This Act shall come into force immediately.
        ///3.   The Acts listed below shall change the short title claus [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_8_original {
            get {
                return ResourceManager.GetString("3john1-8-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 9 - AN ACT REGARDING THE UNION OF THE CROWNS OF THE KINGDOM OF BAUSTRALIA AND THE SECOND KINGDOM OF QUEBEC AND VERSAILLES; REGARDING THE TERMS OF MERGING; REGARDING THE TERMS OF SEPARATION; REGARDING LAW OF SUCCESSION; REGARDING TERMS OF THE KING OF QUEBEC AND VERSAILLES	
        ///
        ///Be it enacted by the King’s most Excellent Majesty, by and with the advice and consent of the Commons, in this present Parliament assembled, and by the authority of the same, as follows:— 
        ///
        ///1.   This Act extends to Baustralia  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_9_amend1 {
            get {
                return ResourceManager.GetString("3john1-9-amend1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CHAPTER 9 - AN ACT REGARDING THE UNION OF THE CROWNS OF THE KINGDOM OF BAUSTRALIA AND THE SECOND KINGDOM OF QUEBEC AND VERSAILLES; REGARDING THE TERMS OF MERGING; REGARDING THE TERMS OF SEPARATION; REGARDING LAW OF SUCCESSION; REGARDING TERMS OF THE KING OF QUEBEC AND VERSAILLES	
        ///
        ///Be it enacted by the Kings most Excellent Majesty, by and with the advice and consent of the Commons, in this present Parliament assembled, and by the authority of the same, as follows: 
        ///
        ///1.   This Act extends to Baustralia  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string _3john1_9_original {
            get {
                return ResourceManager.GetString("3john1-9-original", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap about {
            get {
                object obj = ResourceManager.GetObject("about", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap amended {
            get {
                object obj = ResourceManager.GetObject("amended", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap book {
            get {
                object obj = ResourceManager.GetObject("book", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookOpen {
            get {
                object obj = ResourceManager.GetObject("bookOpen", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap bookSelected {
            get {
                object obj = ResourceManager.GetObject("bookSelected", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap destroyed {
            get {
                object obj = ResourceManager.GetObject("destroyed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap failed {
            get {
                object obj = ResourceManager.GetObject("failed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap in_force {
            get {
                object obj = ResourceManager.GetObject("in_force", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap open {
            get {
                object obj = ResourceManager.GetObject("open", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap opennew {
            get {
                object obj = ResourceManager.GetObject("opennew", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap pending {
            get {
                object obj = ResourceManager.GetObject("pending", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap repealed {
            get {
                object obj = ResourceManager.GetObject("repealed", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap spent {
            get {
                object obj = ResourceManager.GetObject("spent", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
